### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by staffnetDev** [dev7dev/V2ray-Android#16]
I have tried using your project, I compile everything with its libraries and perform a ping before connecting the VPN and it works very well. but after connecting the vpn and giving permission to the VPN app, there is no traffic, they performed a ping and it does not work, android 13, this using android studio 2023. Build #AI-223.8836.35.2231.10811636, built on September 14, 2023

**Comment by staffnetDev** [comment]
---------------------------- PROCESS STARTED (19391) for package dev.dev7.example ----------------------------
2024-05-03 20:28:00.234 19391-19391 ziparchive              dev.dev7.example                     W  Unable to open '/data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/base.dm': No such file or directory
2024-05-03 20:28:00.234 19391-19391 ziparchive              dev.dev7.example                     W  Unable to open '/data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/base.dm': No such file or directory
2024-05-03 20:28:00.282 19391-19391 nativeloader            dev.dev7.example                     D  Configuring clns-4 for other apk /data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/lib/arm64:/data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/dev.dev7.example
2024-05-03 20:28:00.292 19391-19391 GraphicsEnvironment     dev.dev7.example                     V  ANGLE Developer option for 'dev.dev7.example' set to: 'default'
2024-05-03 20:28:00.292 19391-19391 GraphicsEnvironment     dev.dev7.example                     V  ANGLE GameManagerService for dev.dev7.example: false
2024-05-03 20:28:00.292 19391-19391 GraphicsEnvironment     dev.dev7.example                     V  App is not on the allowlist for updatable production driver.
2024-05-03 20:28:00.297 19391-19391 NetworkSecurityConfig   dev.dev7.example                     D  No Network Security Config specified, using platform default
2024-05-03 20:28:00.297 19391-19391 NetworkSecurityConfig   dev.dev7.example                     D  No Network Security Config specified, using platform default
2024-05-03 20:28:00.298 19391-19391 Monotype                dev.dev7.example                     V  SetAppTypeFace- try to flip, app = dev.dev7.example
2024-05-03 20:28:00.301 19391-19391 Monotype                dev.dev7.example                     V      Typeface getFontPathFlipFont - systemFont = default#default
2024-05-03 20:28:00.638 19391-19391 oLibV2RayDaemon         dev.dev7.example                     W  type=1400 audit(0.0:138141): avc: denied { ioctl } for path="pipe:[18542228]" dev="pipefs" ino=18542228 ioctlcmd=0x5413 scontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tcontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tclass=fifo_file permissive=0 app=dev.dev7.example
2024-05-03 20:28:00.638 19391-19391 oLibV2RayDaemon         dev.dev7.example                     W  type=1400 audit(0.0:138142): avc: denied { ioctl } for path="pipe:[18542228]" dev="pipefs" ino=18542228 ioctlcmd=0x5413 scontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tcontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tclass=fifo_file permissive=0 app=dev.dev7.example
2024-05-03 20:28:00.638 19391-19391 oLibV2RayDaemon         dev.dev7.example                     W  type=1400 audit(0.0:138143): avc: denied { ioctl } for path="pipe:[18542228]" dev="pipefs" ino=18542228 ioctlcmd=0x5413 scontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tcontext=u:r:untrusted_app:s0:c137,c258,c512,c768 tclass=fifo_file permissive=0 app=dev.dev7.example
2024-05-03 20:28:00.655 19391-19391 V2rayCoreExecutor       dev.dev7.example                     D  V2rayCoreExecutor -> New initialize from : V2rayVPNService
2024-05-03 20:28:00.675 19391-19391 GoLog                   dev.dev7.example                     I  loading core config
2024-05-03 20:28:00.676 19391-19391 GoLog                   dev.dev7.example                     I  new core
2024-05-03 20:28:00.676 19391-19444 GoLog                   dev.dev7.example                     I  Preparing Domain: dpi.opendnserv.com:443
2024-05-03 20:28:00.676 19391-19391 GoLog                   dev.dev7.example                     I  start core
2024-05-03 20:28:00.676 19391-19437 GoLog                   dev.dev7.example                     I  [Warning] core: Xray 1.8.10 started
2024-05-03 20:28:00.678 19391-19444 GoLog                   dev.dev7.example                     I  Prepare Result:
                                                                                                     Domain: dpi.opendnserv.com
                                                                                                     Port: 443
                                                                                                     IPs: [104.129.129.220]
2024-05-03 20:28:00.689 19391-19391 TUN2SOCKS               dev.dev7.example                     I  T2S Start Commands => [/data/app/~~YTbaIYUOaJ8-oyWCjkbs4w==/dev.dev7.example-85zpblKedvZ2MsWSG758UQ==/lib/arm64/libtun2socks.so, --netif-ipaddr, 26.26.26.2, --netif-netmask, 255.255.255.252, --socks-server-addr, 127.0.0.1:10808, --tunmtu, 1500, --sock-path, sock_path, --enable-udprelay, --loglevel, error, --dnsgw, 127.0.0.1:1053]
2024-05-03 20:28:00.695 19391-19458 SOCK_FILE               dev.dev7.example                     I  connected to sock file [/data/user/0/dev.dev7.example/files/sock_path]
2024-05-03 20:28:02.117  1191-4145  libPowerHal             pid-1191                             E  thermal_pol t=33718, f=36, af=12, ramping=0 tp=0, tgt=0, l=90417, b=227771, p=275375, g=0, X=1, fg=dev.dev7.example, g=0, dgl=0, P=2203mW, chg=Charging, e=0, ff=-1
2024-05-03 20:28:04.835 19299-19333 GoLog                   dev.dev7.example                     I  2024/05/04 00:28:04 [Warning] core: Xray 1.8.10 started
2024-05-03 20:28:07.122  1191-4145  libPowerHal             pid-1191                             E  thermal_pol t=33753, f=3, af=13, ramping=0 tp=0, tgt=0, l=89667, b=221261, p=189541, g=0, X=1, fg=dev.dev7.example, g=0, dgl=0, P=2907mW, chg=Charging, e=0, ff=-1
2024-05-03 20:28:10.808 19391-19418 System                  dev.dev7.example                     W  A resource failed to call close. 
2024-05-03 20:28:10.841 19299-19299 V2rayCoreExecutor       dev.dev7.example                     D  getCurrentServerDelay -> 
                                                                                                    go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
                                                                                                    	at libv2ray.Libv2ray.measureOutboundDelay(Native Method)
                                                                                                    	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor.getConfigDelay(V2rayCoreExecutor.java:162)
                                                                                                    	at dev.dev7.lib.v2ray.V2rayController.getV2rayServerDelay(V2rayController.java:163)
                                                                                                    	at dev.dev7.example.MainActivity.lambda$onCreate$4$dev-dev7-example-MainActivity(MainActivity.java:82)
                                                                                                    	at dev.dev7.example.MainActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242)
                                                                                                    	at android.os.Looper.loop(Looper.java:359)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8111)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)``

**Comment by staffnetDev** [comment]
more my setting is good 

21:06:34.994 LoadedApk                I  Performing receive of Intent { act=V2RAY_SERVICE_STATICS_INTENT flg=0x10 pkg=dev.dev7.example (has extras) }, receiver=dev.dev7.example.MainActivity$1@f75f322, duration=32
21:06:36.052 debug demo               D  getConfigDelay -> {"inbounds":[],"outbounds":[{"mux":{"enabled":false},"protocol":"vmess","settings":{"vnext":[{"address":"xx.xxxxxx.com","port":443,"users":[{"alterId":0,"id":"1bc8a6aa-e24d-41c7-8663-43bcbxxxx728","level":8,"security":"auto"}]}]},"streamSettings":{"network":"ws","security":"tls","tlsSettings":{"allowInsecure":true,"serverName":"domain.com"},"wsSettings":{"headers":{"Host":"domain.com"},"path":"\/ynjWfbS7\a/"}},"tag":"VMESS"}],"policy":{"levels":{"8":{"connIdle":300,"downlinkOnly":1,"handshake":4,"uplinkOnly":1}}},"routing":{"domainStrategy":"IPIfNonMatch"}}
21:06:36.064 GoLog                    I  2024/05/04 01:06:36 [Warning] core: Xray 1.8.10 started
21:06:37.204 libPowerHal              E  thermal_pol t=34350, f=3, af=12, ramping=0 tp=0, tgt=0, l=124094, b=385482, p=733425, g=0, X=1, fg=dev.dev7.example, g=0, dgl=0, P=0mW, chg=Full, e=0, ff=-1
21:06:42.069 V2rayCoreExecutor        D  getCurrentServerDelay -> 
                                         go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
                                         	at libv2ray.Libv2ray.measureOutboundDelay(Native Method)
                                         	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor.getConfigDelay(V2rayCoreExecutor.java:163)
                                         	at dev.dev7.lib.v2ray.V2rayController.getV2rayServerDelay(V2rayController.java:163)
                                         	at dev.dev7.example.MainActivity.lambda$onCreate$4$dev-dev7-example-MainActivity(MainActivity.java:82)
                                         	at dev.dev7.example.MainActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
                                         	at android.os.Handler.handleCallback(Handler.java:942)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loopOnce(Looper.java:242)
                                         	at android.os.Looper.loop(Looper.java:359)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8111)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
21:06:42.069 System.err               W  go.Universe$proxyerror: Get "https://www.google.com/generate_204": net/http: TLS handshake timeout
21:06:42.070 System.err               W  	at libv2ray.Libv2ray.measureOutboundDelay(Native Method)
21:06:42.070 System.err               W  	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor.getConfigDelay(V2rayCoreExecutor.java:163)
21:06:42.070 System.err               W  	at dev.dev7.lib.v2ray.V2rayController.getV2rayServerDelay(V2rayController.java:163)
21:06:42.070 System.err               W  	at dev.dev7.example.MainActivity.lambda$onCreate$4$dev-dev7-example-MainActivity(MainActivity.java:82)
21:06:42.070 System.err               W  	at dev.dev7.example.MainActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
21:06:42.070 System.err               W  	at android.os.Handler.handleCallback(Handler.java:942)
21:06:42.070 System.err               W  	at android.os.Handler.dispatchMessage(Handler.java:99)
21:06:42.071 System.err               W  	at android.os.Looper.loopOnce(Looper.java:242)
21:06:42.071 System.err               W  	at android.os.Looper.loop(Looper.java:359)
21:06:42.071 System.err               W  	at android.app.ActivityThread.main(ActivityThread.java:8111)
21:06:42.071 System.err               W  	at java.lang.reflect.Method.invoke(Native Method)
21:06:42.071 System.err               W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
21:06:42.071 System.err               W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
21:06:42.074 Looper                   W  Slow dispatch took 6036ms main h=android.os.Handler c=dev.dev7.example.MainActivity$$ExternalSyntheticLambda1@d13e9fd m=0
21:06:42.075 Looper                   W  Slow delivery took 6002ms main h=android.view.GestureDetector$GestureHandler c=null m=3

**Comment by dev7dev** [comment]
Hello
I noticed the config you are using is vmess +ws+tls. I tested the same configuration several times in the software and did not see any problems. Please specify whether you are using the uri link?
Email me your config if you are sure there is a problem:
dev7developers@gmail.com
But it seems that this is the problem of your network or configuration.

**Comment by staffnetDev** [comment]
I thought the same thing but I made sure. I have it in use in v2rayNG and from there I exported it and I had a problem with the uri with Jason, the same thing before connecting they performed a ping and everything was fine. but after connecting the vpn the ping does not work anymore there is no traffic

**Comment by staffnetDev** [comment]
friend delete your email you may be bothered with spam if you use telegram I can search for you through aliases

**Comment by dev7dev** [comment]
Hi again.
Test new update and update issue.

**Comment by staffnetDev** [comment]
I will try many today

**Comment by staffnetDev** [comment]
It is a beauty, it works very well, now I will try to use the lib in my project, thank you very much

**Comment by staffnetDev** [comment]
It works great but I kept trying and it doesn't work on my main phone I
tried it on my Samsung s20 plus with Android 13 and everything was fine.
But on my Asus ROG phone 6D Android 14 it doesn't work It gives the same
problem that they had shared with you before. I think incomparable

**Comment by dev7dev** [comment]
Have you tested other configurations on your Asus phone?
It seems that there is a network problem in your Asus device, I want to know if this problem is caused in the library or not.

**Comment by staffnetDev** [comment]
hello Dev7
I have solved the problem with your app, I tried to make a commit in git but it is not allowed. Now I can use my configurations depending on the type of protocol: ws tcp quick kcp, I tried only three but I think the others are fine now without any problems it works. I would like to make the contribution through my github account

**Comment by staffnetDev** [comment]
The main problem is how the json data parse is being managed, there are missing parameters in the json structure.

 Your library is great, it has been useful to me, thank you very much, I hope it contributes something to your project.

**Comment by dev7dev** [comment]
Hi ,
That great .
please create a fork from library and commit it or share more details with us if possible.
