### ISSUE TITLE
stuck on connecting

### ISSUE THREAD

**Issue by farzinAndroid** [dev7dev/V2ray-Android#20]
i have done exactly as the doc but when i use the main app it works fine but when i use the module in my own app it doesnt work

**Comment by dev7dev** [comment]
Hi
we need more information please send us a log or more detail.

**Comment by farzinAndroid** [comment]
sure.
when i use VPN mode i get this error (the proxy mode gets connected but doesnt work):
```
java.lang.IllegalArgumentException: Receiver not registered: dev.dev7.lib.v2ray.services.V2rayVPNService$1@a9405f9
                                                                                                    	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
                                                                                                    	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
                                                                                                    	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.onDestroy(V2rayVPNService.java:255)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.setupService(V2rayVPNService.java:189)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.startService(V2rayVPNService.java:271)
                                                                                                    	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor$1.setup(V2rayCoreExecutor.java:68)
                                                                                                    	at libv2ray.V2RayPoint.runLoop(Native Method)
                                                                                                    	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor.startCore(V2rayCoreExecutor.java:99)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.onStartCommand(V2rayVPNService.java:141)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

```
Tun2socks Run Error =>> java.io.IOException: Cannot run program "/data/app/~~jtN42cKEkUTk25JsQzNlqw==/com.farzin.testv2rayxml-8weXK9szPp6KHxeElcQlEw==/lib/x86_64/libtun2socks.so" (in directory "/data/user/0/com.farzin.testv2rayxml/files"): error=2, No such file or directory

```

                                                     	
 eventhough i used exactly you code but in a diffrent project for testing reasons. i appriciate it if you could help me.

**Comment by dev7dev** [comment]
What is your own project`s gradle and gradle plugin version?

Add this code in v2ray module monifest in application tag :
` <application
        android:extractNativeLibs="true"
        tools:targetApi="m">`

And test your application again if  you app successfuly connected and disconnected tell me to commit that to repo.

**Comment by farzinAndroid** [comment]
unfortunately no still getting the same error (i added you line in the module manifest)

```

Tun2socks Run Error =>> java.io.IOException: Cannot run program "/data/app/~~7qB6-j0MiHGQgtUbOP90AQ==/com.farzin.testv2rayxml-fTW1IvqQFicm-_LcGCgrzQ==/lib/x86_64/libtun2socks.so" (in directory "/data/user/0/com.farzin.testv2rayxml/files"): error=2, No such file or directory
2024-05-29 15:35:22.221 21350-21350 V2rayCoreExecutor       com.farzin.testv2rayxml              D  setupFailed =>  (Ask Gemini)
                                                                                                    java.lang.IllegalArgumentException: Receiver not registered: dev.dev7.lib.v2ray.services.V2rayVPNService$1@5fd6ff2
                                                                                                    	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
                                                                                                    	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
                                                                                                    	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.onDestroy(V2rayVPNService.java:255)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.setupService(V2rayVPNService.java:189)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.startService(V2rayVPNService.java:271)
                                                                                                    	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor$1.setup(V2rayCoreExecutor.java:68)
                                                                                                    	at libv2ray.V2RayPoint.runLoop(Native Method)
                                                                                                    	at dev.dev7.lib.v2ray.core.V2rayCoreExecutor.startCore(V2rayCoreExecutor.java:99)
                                                                                                    	at dev.dev7.lib.v2ray.services.V2rayVPNService.onStartCommand(V2rayVPNService.java:141)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-05-29 15:35:22.992 21275-21384 ProfileInstaller        com.farzin.testv2rayxml              D  Installing profile for com.farzin.testv2rayxml

```

**Comment by dev7dev** [comment]
What is your own project`s gradle and gradle plugin version?

**Comment by farzinAndroid** [comment]
okay i played around with the manifest code you gave me and i fixed it heres how

you should add these lines : 
``` 
android:usesCleartextTraffic="true"
        android:extractNativeLibs="true"
```
in you MAIN application manifest

and you should add these :
```
<application
        android:extractNativeLibs="true"
        tools:targetApi="m">
```

in your V2RAY module manifest.(:

**Comment by farzinAndroid** [comment]
i also have another Q :
can you please tell me in which part of your code the config string gets converted to JSON?
i appreciate it bro thanks.

**Comment by dev7dev** [comment]
Basically, it shouldn't matter in which manifest the code is placed, probably your problem is solved by adding the usesCleartextTraffic code.
We use [uri-to-json](https://github.com/dev7dev/uri-to-json) in [ Dev7 customized android xray lib ](https://github.com/dev7dev/AndroidLibXrayLite). 
In android moudle with [this function](https://github.com/dev7dev/V2ray-Android/blob/d1a4d2e19d6f3d072f27723b7a7f5a5262b77f0b/v2ray/src/main/java/dev/dev7/lib/v2ray/utils/Utilities.java#L100) we checking and trying to convert uri to json with native codes.
